INSERT INTO target_db.violation(
  "activity_nr"
  , "citation_id"
  , "delete_flag"
  , "standard"
  , "viol_type"
  , "issuance_date"
  , "abate_date"
  , "abate_complete"
  , "current_penalty"
  , "initial_penalty"
  , "contest_date"
  , "final_order_date"
  , "nr_instances"
  , "nr_exposed"
  , "rec"
  , "gravity"
  , "emphasis"
  , "hazcat"
  , "fta_insp_nr"
  , "fta_issuance_date"
  , "fta_penalty"
  , "fta_contest_date"
  , "fta_final_order_date"
  , "hazsub1"
  , "hazsub2"
  , "hazsub3"
  , "hazsub4"
  , "hazsub5"
  , "load_dt"
)
SELECT
  "activity_nr"
  , "citation_id"
  , CONVERT_XYN_BOOLEAN("delete_flag")
  , "standard"
  , "viol_type"
  , "issuance_date"
  , "abate_date"
  , "abate_complete"
  , "current_penalty"
  , "initial_penalty"
  , "contest_date"
  , "final_order_date"
  , "nr_instances"
  , "nr_exposed"
  , "rec"
  , "gravity"
  , CONVERT_XYN_BOOLEAN("emphasis")
  , "hazcat"
  , "fta_insp_nr"
  , "fta_issuance_date"
  , "fta_penalty"
  , "fta_contest_date"
  , "fta_final_order_date"
  , "hazsub1"
  , "hazsub2"
  , "hazsub3"
  , "hazsub4"
  , "hazsub5"
  , SUBSTR(load_dt, 1, 10)

FROM src_db.violation
;
