INSERT INTO target_db.accident_injury(
    "summary_nr"
    , "rel_insp_nr"
    , "age"
    , "sex"
    , "nature_of_inj"
    , "part_of_body"
    , "src_of_injury"
    , "event_type"
    , "evn_factor"
    , "hum_factor"
    , "occ_code"
    , "degree_of_inj"
    , "task_assigned"
    , "hazsub"
    , "const_op"
    , "const_op_cause"
    , "fat_cause"
    , "fall_ht"
--    , "load_dt"
)
SELECT
      LEFT_ZERO_PAD("summary_nr", 9) AS "summary_nr"
    , LEFT_ZERO_PAD("rel_insp_nr", 9) AS "rel_insp_nr"
    , "age"
    , "sex"
    , "nature_of_inj"
    , "part_of_body"
    , "src_of_injury"
    , "event_type"
    , "evn_factor"
    , "hum_factor"
    , "occ_code"
    , "degree_of_inj"
    , "task_assigned"
    , "hazsub"
    , "const_op"
    , "const_op_cause"
    , "fat_cause"
    , "fall_ht"
 --   , SUBSTR(load_dt, 1, 10)

FROM src_db.accident_injury
;
